# Generated by Django 4.2.3 on 2023-07-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('user_full_name', models.CharField(max_length=50, unique=True)),
                ('job_title', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('software_user_name', models.CharField(max_length=50, unique=True)),
                ('expiration_date', models.DateField()),
                ('version', models.CharField(max_length=10)),
            ],
        ),
    ]
